Body content
rbd3/Andry pull request #2
Opened 2023-03-29 16:41 UTC by rbd3

Write html and css code.

2023-03-30 22:13 UTC, Strangeal requested changes
Hi @rbd3, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)
## Highlights


## Required Changes ♻️
- [ ] Please be sure to stick to the Figma design templates as closely as possible. Kindly adjust your spacing in the work section to match the Figma design.
Figma: 
<img width="331" alt="Screenshot 2023-03-30 at 21 50 15" src="https://user-images.githubusercontent.com/107192076/228973963-574487d2-9621-4233-adf0-24ba4d746ef7.png">

Your design:
<img width="327" alt="Screenshot 2023-03-30 at 21 52 00" src="https://user-images.githubusercontent.com/107192076/228974490-1763a3bd-6cc9-4738-bb03-11698104f2d1.png">

- [ ] Please make sure your image expands full width so it looks like the Figma design.

- [ ] In the below screenshot you can see the `>` is overflowing on the word **Framework**. Please correct that and make it match the Figma design.
Figma:
<img width="370" alt="Screenshot 2023-03-30 at 22 10 52" src="https://user-images.githubusercontent.com/107192076/228975530-196abf37-728e-4a7e-982e-46b17113f151.png">

Your design:
<img width="327" alt="Screenshot 2023-03-30 at 22 07 51" src="https://user-images.githubusercontent.com/107192076/228975559-24cc61ce-dd1b-4961-acb4-60d60bd2ee77.png">


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 22:13 UTC, Strangeal commented on index.html
> +        <h1 class="about-text">About Myself</h1>
Kindly change this `h1` tag and instead use other header tags`(h2 - h6)`. 

Using only one `h1` creates hierarchy and gives your page a more logical structure. It makes it easy for readers (and those using screen readers) to skim and understand what your page is about. Each page should have only one main topic and headline. And that should be your only `h1`

2023-03-30 22:13 UTC, Strangeal commented on index.html
> +        </ul>
Great work listing all the icons beautifully 🤩.  Let's improve it a bit to more by making it more semantically correct. Instead of having `li` tags inside the `a` tags, use should rather have the `a` tags inside the `li` tags. Example:
```
It should be like below

<li>
  <a></a>
</li>
```

2023-03-31 17:56 UTC, Zuhaib042 approved these changes
Hi @rbd3 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/13zeE9qQNC5IKk/giphy.gif)



## Optional suggestions
- [ ] Kindly consider giving your `body` tag `margin: 0` because it is taking `margin: 8px` default which doesn't look good on your project.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 18:41 UTC, merged